<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllwithCategory(){
        return $this->createQueryBuilder("p")
            ->leftJoin("p.category","c")
            ->addSelect("c")
            ->orderBy("p.createdAt","Desc")
            ->getQuery()
            ->getResult();
    }
}
